name: hello-world workflow
on: [push, workflow_dispatch]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      -  name: print hello-world
         run: echo "Hellow World"

  second_job:
    runs-on: ubuntu_latest
    steps:
      - name: Bye world
        run: echo "Bye Bye"
        

