name: hello-world workflow
on: [workflow_dispatch,]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      -  name: git checkout
         uses: actions/checkout@v4
      - name: list of files
        run: ls -lrth

  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Bye world
        run: echo "Bye Bye"

  third_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Ask Beer
        run: echo "Where are you Beer?"

